# E-commerce Product Data Extraction & Processing Using REST API

## Objective

Extract e-commerce product data from a REST API, process and clean the JSON response using Python and Pandas, validate the dataset, create useful derived fields, and export the final dataset as a CSV file ready for data analysis.

#### 1. Importing Libraries

In [1]:
import requests
import pandas as pd

#### 2. API Connection

In [2]:
url = "https://dummyjson.com/products"
response = requests.get(url)

print("Status Code:", response.status_code)

Status Code: 200

In [3]:
response.raise_for_status()

#### 3. Data Extraction

In [4]:
params = {"limit": 0}

response = requests.get(url, params=params)
response.raise_for_status()

data = response.json()

print("Total Products:", data["total"])
print("Products Received:", len(data["products"]))

Total Products: 194
Products Received: 194

#### 4. JSON → Pandas DataFrame

In [5]:
df = pd.DataFrame(data["products"])

print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset Shape: (194, 22)

Columns:
['id', 'title', 'description', 'category', 'price', 'discountPercentage', 'rating', 'stock', 'tags', 'brand', 'sku', 'weight', 'dimensions', 'warrantyInformation', 'shippingInformation', 'availabilityStatus', 'reviews', 'returnPolicy', 'minimumOrderQuantity', 'meta', 'images', 'thumbnail']

In [6]:
df.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-10-09T14:47:01.588Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2024-12-03T11:29:45.706Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-01-08T18:30:12.844Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-11-22T23:28:00.911Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-10-03T07:39:53.470Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    194 non-null    int64
 1   title                 194 non-null    object
 2   description           194 non-null    object
 3   category              194 non-null    object
 4   price                 194 non-null    float64
 5   discountPercentage    194 non-null    float64
 6   rating                194 non-null    float64
 7   stock                 194 non-null    int64
 8   tags                  194 non-null    object
 9   brand                 102 non-null    object
 10  sku                   194 non-null    object
 11  weight                194 non-null    int64
 12  dimensions            194 non-null    object
 13  warrantyInformation   194 non-null    object
 14  shippingInformation   194 non-null    object
 15  availabilityStatus    194 non-null    object
 16  reviews               194 non-null    object
 17  returnPolicy          194 non-null    object
 18  minimumOrderQuantity  194 non-null    int64
 19  meta                  194 non-null    object
 20  images                194 non-null    object
 21  thumbnail             194 non-null    object
dtypes: float64(3), int64(4), object(15)
memory usage: 33.5+ KB

#### 5. Missing values

In [8]:
missing_values = df.isnull().sum()

print(missing_values[missing_values > 0])

brand    92
dtype: int64

#### 6. Selecting Analysis Columns

In [9]:
analysis_cols = [
    "id",
    "title",
    "category",
    "price",
    "discountPercentage",
    "rating",
    "stock",
    "brand",
    "sku",
    "weight",
    "availabilityStatus",
    "returnPolicy",
    "minimumOrderQuantity"
]

df_analysis = df[analysis_cols].copy()

print("Analysis Dataset Shape:", df_analysis.shape)

Analysis Dataset Shape: (194, 13)

In [10]:
df_analysis.head()

,id,title,category,price,discountPercentage,rating,stock,brand,sku,weight,availabilityStatus,returnPolicy,minimumOrderQuantity
0,1,Essence Mascara Lash Princess,beauty,9.99,10.48,2.56,99,Essence,BEA-ESS-ESS-001,4,In Stock,No return policy,48
1,2,Eyeshadow Palette with Mirror,beauty,19.99,18.19,2.86,34,Glamour Beauty,BEA-GLA-EYE-002,9,In Stock,7 days return policy,20
2,3,Powder Canister,beauty,14.99,9.84,4.64,89,Velvet Touch,BEA-VEL-POW-003,8,In Stock,No return policy,22
3,4,Red Lipstick,beauty,12.99,12.16,4.36,91,Chic Cosmetics,BEA-CHI-LIP-004,1,In Stock,7 days return policy,40
4,5,Red Nail Polish,beauty,8.99,11.44,4.32,79,Nail Couture,BEA-NAI-NAI-005,8,In Stock,No return policy,22

### 7. Data Cleaning

#### 7.1. Handling Missing Values

In [11]:
df_analysis["brand"] = df_analysis["brand"].fillna("Unknown")

print("Missing brand values:", df_analysis["brand"].isnull().sum())

Missing brand values: 0

#### 7.2. Duplicate Product IDs

In [12]:
duplicate_ids = df_analysis["id"].duplicated().sum()

print("Duplicate Product IDs:", duplicate_ids)

Duplicate Product IDs: 0

#### 7.3. Duplicate SKUs

In [13]:
duplicate_skus = df_analysis["sku"].duplicated().sum()

print("Duplicate SKUs:", duplicate_skus)

Duplicate SKUs: 0

### 8. Data Validation

#### 8.1. Negative Prices

In [14]:
negative_prices = (df_analysis["price"] < 0).sum()

print("Negative Prices:", negative_prices)

Negative Prices: 0

#### 8.2. Negative Stock

In [15]:
negative_stock = (df_analysis["stock"] < 0).sum()

print("Negative Stock:", negative_stock)

Negative Stock: 0

#### 8.3 Invalid Discounts

In [16]:
invalid_discounts = (
    (df_analysis["discountPercentage"] < 0) |
    (df_analysis["discountPercentage"] > 100)
).sum()

print("Invalid Discounts:", invalid_discounts)

Invalid Discounts: 0

#### 8.4. Invalid Ratings

In [17]:
invalid_ratings = (
    (df_analysis["rating"] < 0) |
    (df_analysis["rating"] > 5)
).sum()

print("Invalid Ratings:", invalid_ratings)

Invalid Ratings: 0

#### 8.5. Invalid Minimum Order Quantities

In [18]:
invalid_min_qty = (
    df_analysis["minimumOrderQuantity"] <= 0
).sum()

print("Invalid Minimum Order Quantities:", invalid_min_qty)

Invalid Minimum Order Quantities: 0

### 9. Feature Engineering

#### 9.1. Discount Amount

In [19]:
df_analysis["Discount_Amount"] = (
    df_analysis["price"] *
    df_analysis["discountPercentage"] / 100
).round(2)

#### 9.2. Discounted Price

In [20]:
df_analysis["Discounted_Price"] = (
    df_analysis["price"] -
    df_analysis["Discount_Amount"]
).round(2)

#### 9.3. Inventory Value

In [21]:
df_analysis["Inventory_Value"] = (
    df_analysis["price"] *
    df_analysis["stock"]
).round(2)

#### 9.4. Discounted Inventory Value

In [22]:
df_analysis["Discounted_Inventory_Value"] = (
    df_analysis["Discounted_Price"] *
    df_analysis["stock"]
).round(2)

#### 9.5. Discount Band

In [23]:
def discount_band(discount):
    if discount == 0:
        return "No Discount"
    elif discount <= 10:
        return "Low"
    elif discount <= 25:
        return "Medium"
    else:
        return "High"

df_analysis["Discount_Band"] = (
    df_analysis["discountPercentage"].apply(discount_band)
)

#### 9.6. Stock Status

In [24]:
def stock_status(stock):
    if stock == 0:
        return "Out of Stock"
    elif stock <= 20:
        return "Low Stock"
    elif stock <= 50:
        return "Medium Stock"
    else:
        return "High Stock"

df_analysis["Stock_Status"] = (
    df_analysis["stock"].apply(stock_status)
)

#### 10. Final Validation

In [25]:
print("Final Dataset Shape:", df_analysis.shape)

print("\nMissing Values:")
print(df_analysis.isnull().sum().sum())

print("\nDuplicate Rows:")
print(df_analysis.duplicated().sum())

Final Dataset Shape: (194, 19)

Missing Values:
0

Duplicate Rows:
0

In [26]:
df_analysis.head()

,id,title,category,price,discountPercentage,rating,stock,brand,sku,weight,availabilityStatus,returnPolicy,minimumOrderQuantity,Discount_Amount,Discounted_Price,Inventory_Value,Discounted_Inventory_Value,Discount_Band,Stock_Status
0,1,Essence Mascara Lash Princess,beauty,9.99,10.48,2.56,99,Essence,BEA-ESS-ESS-001,4,In Stock,No return policy,48,1.05,8.94,989.01,885.06,Medium,High Stock
1,2,Eyeshadow Palette with Mirror,beauty,19.99,18.19,2.86,34,Glamour Beauty,BEA-GLA-EYE-002,9,In Stock,7 days return policy,20,3.64,16.35,679.66,555.90,Medium,Medium Stock
2,3,Powder Canister,beauty,14.99,9.84,4.64,89,Velvet Touch,BEA-VEL-POW-003,8,In Stock,No return policy,22,1.48,13.51,1334.11,1202.39,Low,High Stock
3,4,Red Lipstick,beauty,12.99,12.16,4.36,91,Chic Cosmetics,BEA-CHI-LIP-004,1,In Stock,7 days return policy,40,1.58,11.41,1182.09,1038.31,Medium,High Stock
4,5,Red Nail Polish,beauty,8.99,11.44,4.32,79,Nail Couture,BEA-NAI-NAI-005,8,In Stock,No return policy,22,1.03,7.96,710.21,628.84,Medium,High Stock

#### 11. Exporting to CSV

In [27]:
output_file = r"C:\Users\narla\Downloads\Ecommerce Product_Data Extraction_API\ecommerce_products_cleaned.csv"

df_analysis.to_csv(output_file, index=False)

print(f"CSV file created successfully: {output_file}")

CSV file created successfully: C:\Users\narla\Downloads\Ecommerce Product_Data Extraction_API\ecommerce_products_cleaned.csv